name: Mirror to Private Repository

on:
  push:
    branches:
      - main
      - PROD-14446

jobs:
  mirror:
    if: github.repository == 'projectxyzio/appium-inspector'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Public Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Push to Private Mirror
        env:
          DESTINATION_REPO: https://x-access-token:${{ secrets.MIRROR_PAT }}@github.com/projectxyzio/appium-inspector-internal.git
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          git remote add private $DESTINATION_REPO
          git push private HEAD:refs/heads/$BRANCH_NAME --force
