name: Semantic Release
on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    if: github.repository == 'projectxyzio/appium-inspector-internal'
    uses: projectxyzio/gh-actions/.github/workflows/semantic-release.yml@master
    permissions:
      contents: write
      issues: write
      pull-requests: write
    with:
      branches: '["main"]'
      npm-install-flags: '--no-save --ignore-scripts'
      delete-tags-glob: 'v20*'
    secrets: inherit
